### ISSUE TITLE
Sponsor this project

### ISSUE THREAD

**Issue by marcelosousa** [ohler55/ojg#102]
Hi! We're going to start using this project as a dependency to [reviewpad](https://github.com/reviewpad/reviewpad). It is our policy to try to sponsor all open source projects that we use. Is there a way to do this? FYI: We typically do GitHub sponsors.

**Comment by ohler55** [comment]
That sounds great! I'll check into GitHub sponsors. That is as good as any.

**Comment by ohler55** [comment]
GitHub sponsors for OjG has been set up.

**Comment by ohler55** [comment]
Ok, to close this issue now that GitHub sponsor has been set up.
