### ISSUE TITLE
Getting full path of a rule in the json

### ISSUE THREAD

**Issue by LironKS** [ohler55/ojg#111]
Hi, 
Thank you for this contribution, it's very helpful :)

I'm looking for a method that for a given rule is returning a list of the full paths it appears in the json. 
For example, my json is:
`{
  "name": "John Smith",
  "male": true,
  "age": 35,
  "address": "New York",
  "null": null,
  "metadata": {
    "date": "2022-04-01T00:00:00.000Z",
    "count": "5",
    "name": "John Smith"
  },
  "test": {
    "name": "John Smith"
  }
}`

and the rule is:  `"$.*.name"`

So I want to have  something like this: `["$.metadata.name","$.test.name"]`

Is there any method that does this?

Thanks.

**Comment by ohler55** [comment]
There is not at this point in time.

**Comment by ohler55** [comment]
Does the jp Locate() function do what you were looking for?

**Comment by Skeeve** [comment]
It does.

```go
package main

import (
	"fmt"
	"github.com/ohler55/ojg/jp"
	"github.com/ohler55/ojg/oj"
)

func main() {
	jsonDataString := `{
		"name": "John Smith",
		"male": true,
		"age": 35,
		"address": "New York",
		"null": null,
		"metadata": {
			"date": "2022-04-01T00:00:00.000Z",
			"count": "5",
			"name": "John Smith"
		},
		"test": {
			"name": "John Smith"
		}
	}`
	data, _ := oj.ParseString(jsonDataString)

	myJP := jp.MustParseString(`$.*.name`)
	myLoc := myJP.Locate(data, 0)
	fmt.Printf("%+v\n", myLoc)
}
```

Output

```
[$.metadata.name $.test.name]
```

[Run on playgroud](https://play.golang.com/p/D16aNEbOCmX)
