### ISSUE TITLE
Array indexes with last return reverse order

### ISSUE THREAD

**Issue by lsytj0413** [ohler55/ojg#118]
Give this code:

```
	expr, err := jp.ParseString("$.vals[-3:]")
	if err != nil {
		panic(err)
	}

	result := expr.Get(map[string]interface{}{
		"vals": []int{0, 10, 20, 30, 40, 50},
	})
	fmt.Printf("result: %v\n", result)
```

the result is: `[50 40 30]`，but it should be `[30 40 50]`，evaluated at https://jsonpath.com/ 

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/6871552/223008034-5f04e134-36b8-482e-b6a3-ce2f606bc15f.png">

version: v1.17.5

**Comment by ohler55** [comment]
I'll get it fixed.

**Comment by ohler55** [comment]
Did release v1.18.0 and later fix the issue?

**Comment by ohler55** [comment]
No response, closing.

**Comment by lsytj0413** [comment]
> Did release v1.18.0 and later fix the issue?

Sorry for the late reply. I have test it on  v1.18.5，this have been fixed.
