### ISSUE TITLE
Provides the length functionality

### ISSUE THREAD

**Issue by ayadav111** [ohler55/ojg#137]
Hi,

I am using your library for JSON path filter and I wanted to use length functionality sothat it can provides the length of an array in a given JSON but I couldn't find out. 

<html>
<body>

length() | Provides the length of an array | Integer
-- | -- | --

</body>
</html>

Jayway jsonpath is having this functionality. ref: https://github.com/json-path/JsonPath
Can we have the same here ?
Thank you!

**Comment by ohler55** [comment]
Please re-check the documentation https://pkg.go.dev/github.com/ohler55/ojg/jp#Script. The length function is supported in OjG. You can construct a script directly or `length(@.x)` can be used in a filter expression.
