### ISSUE TITLE
Panic on setting a nil value on JSONPath

### ISSUE THREAD

**Issue by nervo** [ohler55/ojg#146]
A panic occurs when trying to set a `nil` value on a JSONPath

See the following playground: https://go.dev/play/p/pyYYcThozY9

```golang
package main

import (
	"fmt"

	"github.com/ohler55/ojg/jp"
)

func main() {
	data := map[string]any{
		"foo": nil,
		"bar": 0,
		"baz": "",
	}
	fmt.Println(data)

	path, _ := jp.ParseString("foo")

	path.Set(&data, 123) // No panic, value is set
	fmt.Println(data)

	path.Set(&data, nil)  // Panic occurs :)
	fmt.Println(data)
}
```

By the way, i'm just testing your lib who seems to be amazing :)

**Comment by ohler55** [comment]
I'll get that fixed this weekend.

**Comment by ohler55** [comment]
I forgot to make the release with the fix. Actually fixed it Friday night but then forgot to checkin and release. v1.20.1 will be out in a few moments.

**Comment by nervo** [comment]
Aaaaand it works \o/

Good job, and thanks for the fix @ohler55 :)
