### ISSUE TITLE
oj.Unmarshal fails on arrays

### ISSUE THREAD

**Issue by right-mouse** [ohler55/ojg#151]
Simple example:

```go
var f [4]int
err := oj.Unmarshal(`[1,2,3,4]`, &f)
```

The following error is returned: `reflect.MakeSlice of non-slice type`

Playground: https://go.dev/play/p/Qasyi87zIFb

**Comment by ohler55** [comment]
Please try the "arrays" branch. The example will not work as Unmarshal converts all numbers to float64 what can not be assigned to ints. Parse should work though. I still have some more edge case to test and need to compare to the core json library to see if it handles the example.

**Comment by ohler55** [comment]
ok, updated to handle the test case. Should be ready.

**Comment by ohler55** [comment]
Released v1.21.0

**Comment by right-mouse** [comment]
Works as expected. Thanks for the fix.
