### ISSUE TITLE
Add jp.Expr.Locate()

### ISSUE THREAD

**Issue by ohler55** [ohler55/ojg#153]
Add a function that given an JSONPath expression returns the normalized paths to all the matching elements.

**Comment by xujianjun2000** [comment]
looking forword to this new function really~~~

**Comment by ohler55** [comment]
The development branch is "jp-locate". Currently adding tests which will be followed by support for reflection.

**Comment by xujianjun2000** [comment]
> The development branch is "jp-locate". Currently adding tests which will be followed by support for reflection.
Ohler,
Bravo！！！
Absolutely stunning！

**Comment by ohler55** [comment]
Release after fixing the unmarshal `[4]int` bug

**Comment by xujianjun2000** [comment]
> Release after fixing the unmarshal `[4]int` bug

AweAsome！Which version would be released with it?

**Comment by ohler55** [comment]
Release v1.21.0 on Dec 18th.

**Comment by xujianjun2000** [comment]
> Release v1.21.0 on Dec 18th.

Hello, Ohler, back again, the lastest release version is v1.19.4, can it use the tagged version v1.21.0 as a released version?
It is also stable (tagged version)?

**Comment by ohler55** [comment]
If it is tagged then it is stable or at least I believe it is stable.

**Comment by xujianjun2000** [comment]
> If it is tagged then it is stable or at least I believe it is stable.

Ok，thanks for reply, Ohler. You believe tag, I believe you, so I believe tag too! ^-^~
