### ISSUE TITLE
cmd/og: missing package documentation

### ISSUE THREAD

**Issue by dolmen** [ohler55/ojg#16]
Command [`github.com/ohler55/ojg/cmd/oj`](https://pkg.go.dev/github.com/ohler55/ojg/cmd/oj?tab=doc) lacks package documentation.

**Comment by ohler55** [comment]
I'll get that in tonight. The command itself does include documentation with the `-h` option.

**Comment by dolmen** [comment]
Fixed by #17 (merged).
