### ISSUE TITLE
Consider implementing JSONPath

### ISSUE THREAD

**Issue by glyn** [ohler55/ojg#163]
IETF [RFC 9535](https://www.rfc-editor.org/rfc/rfc9535) defines a proposed standard for JSONPath. Other resources:

* A partial [Compliance Test Suite](https://github.com/jsonpath-standard/jsonpath-compliance-test-suite).
* Behaviours of various implementations can be checked in the [comparison project](https://cburgmer.github.io/json-path-comparison/). Please note that the JSONPath Reference Implementation referenced in the comparison project is stalled/archived and incomplete.
* At the time of writing, online sandboxes for RFC 9535 are available [in C#](https://json-everything.net/json-path) and [in Rust](https://serdejsonpath.live/).
* For more background and comments on the status of the CTS and RI, see this [this post](https://underlap.org/jsonpath-from-blog-post-to-rfc-in-17-years) (also [here](https://www.ietf.org/blog/jsonpath-rfc/) in the IETF blog).
* Public discussion occurs in the IETF JSONPath Working Group's [mailing list](https://www.ietf.org/mailman/listinfo/jsonpath) ([archive](https://mailarchive.ietf.org/arch/browse/jsonpath/)).

(See [here](https://underlap.org/implementing-jsonpath-rfc-9535) for updates to this list of resources.)

Valid approaches for this project are to (a) implement the RFC in whole or in part, (b) document its behaviour relative to the RFC, and (c) do nothing.

**Comment by ohler55** [comment]
Why is this an issue? Have you looked at OjG at all or the jp package of OjG?

**Comment by glyn** [comment]
> Why is this an issue? Have you looked at OjG at all or the jp package of OjG?

I'm afraid I haven't had time, sorry - the issue is just one of many I'm raising to notify implementers. If there is nothing to do or no intention to do anything, please feel free to close this issue.

**Comment by ohler55** [comment]
It is really inappropriate to spam implementors forcing them to waste time simply due to your own laziness. We work hard to provide software that others find helpful. Please be more considerate in the future. If you are going to raise an issue make sure it is appropriate and don't make demands on how to respond with an a, b, or c choice.

**Comment by glyn** [comment]
My sincere apologies for wasting your time and thanks for helping me understand your perspective.

**Comment by ohler55** [comment]
Thank you. I think you just a hit a nerve. OjG does in fact attempt to follow the RFC which is mentioned in the README.md file. I believe OjG is the most complete go implementation of JSONPath so far. I have commented on issue on the RFC github project and have a new issue or PR to bring up based on a choice I made in the JSONPath implementation in OjG.

**Comment by glyn** [comment]
Thanks. I'm currently bumping @gregsdennis's JsonPath.Net to v1.0.0 on the comparison project as that also implements the RFC. Then it will be fun to play "spot the difference" between that column and OjG's.

**Comment by ohler55** [comment]
There are still some gray areas in the spec and a lot of details to get right. I'm sure there will be differences but hopefully the gaps are getting smaller.

**Comment by glyn** [comment]
Yes, hopefully. If you want to log any of the gray areas, it's probably easiest to drop an issue in the spec repo. (Although I've unsubscribed, others in the JSONPath Working Group haven't).

**Comment by ohler55** [comment]
That is the plan. I should probably stop putting it off and submit the issue. BTW, I noticed the comparison by @cburgmer is out of date for OjG so I'll reach out and try to get that updated.
