### ISSUE TITLE
Compile failed for the reason that the tag v1.12.8 has been deleted

### ISSUE THREAD

**Issue by wzqhbustb** [ohler55/ojg#173]
Hi there,

The ojg is a JSON transform library that our product heavily relies on. We are extremely grateful for providing such a high-performance JSON parsing library. However, recently, many of our customers have encountered compilation issues when using an older version of our product. The problem stems from the deletion of the v1.12.8 tag.

Due to certain circumstances, our clients are unable to upgrade the version and tag of ojg. Could you please restore the original v1.12.8 tag? This is crucial for us. We understand that the situation is peculiar, as it involves an inability to upgrade to a newer version. However, the matter is urgent and unexpected. We greatly appreciate your help and support.

```
go: downloading [github.com/ohler55/ojg](http://github.com/ohler55/ojg) v1.12.8
src/server/transform/json/json.go:11:2: [github.com/ohler55/ojg@v1.12.8](http://github.com/ohler55/ojg@v1.12.8): reading https://goproxy.io/github.com/ohler55/ojg/@v/v1.12.8.zip: 404 Not Found
        server response: not found: [github.com/ohler55/ojg@v1.12.8](http://github.com/ohler55/ojg@v1.12.8): invalid version: unknown revision v1.12.8
src/server/transform/json/json.go:12:2: [github.com/ohler55/ojg@v1.12.8](http://github.com/ohler55/ojg@v1.12.8): reading https://goproxy.io/github.com/ohler55/ojg/@v/v1.12.8.zip: 404 Not Found
        server response: not found: [github.com/ohler55/ojg@v1.12.8](http://github.com/ohler55/ojg@v1.12.8): invalid version: unknown revision v1.12.8
make: *** [Makefile:36：mxgate] Error 1
```

many thanks.

**Comment by ohler55** [comment]
Put the tag back. I highly encourage moving to a newer version though.

**Comment by ohler55** [comment]
okay to close?
