### ISSUE TITLE
feature request: want Del method return the deleted elements

### ISSUE THREAD

**Issue by jujiale** [ohler55/ojg#183]
hello, I find in Del method.
`

     // Del removes matching nodes.
    func (x Expr) Del(data any) error {
	    return x.set(data, delFlag, "delete", false)
    }

`

could **ojg** provide a del method. which could return those elements who have been deleted, thanks.

**Comment by ohler55** [comment]
That's a possibility. It would not be as performant and it would think returning both path and value would be best.

Alternatively a delete with a callback is another option.

**Comment by ohler55** [comment]
I think the callback approach will be best. Not sure when I will have it done though.

**Comment by jujiale** [comment]
thanks，I will also research how to achieve this.   if done. I will submit a pr.

**Comment by ohler55** [comment]
The jp.Modify might be a good example of how to implement. Not exactly the same but similar. It also depends on whether the delete should replace items in a list with nil or remove from list.

**Comment by ohler55** [comment]
I've started a branch names expr-walk. The plan is to implement `func (x Expr) Walk(data any, cb func(path Expr, data, parent any))`. That will walk the matching nodes and allow the `cb` function to modify and/or collect matching nodes. It should be easy to implement a delete that returns the deleted values along with the path the deleted value was found at with this new function.

**Comment by jujiale** [comment]
> I've started a branch names expr-walk. The plan is to implement `func (x Expr) Walk(data any, cb func(path Expr, data, parent any))`. That will walk the matching nodes and allow the `cb` function to modify and/or collect matching nodes. It should be easy to implement a delete that returns the deleted values along with the path the deleted value was found at with this new function.

thanks, that's awesome, I will have a look.

**Comment by jujiale** [comment]
> Only started the branch. Not even close to being ready for use. Just letting you know in case you wanted to keep an eye on it.

OK，get it!

**Comment by ohler55** [comment]
The expr-walk branch is ready to be merged. I plan on merging and releasing tomorrow unless someone such as yourself has comments about it.
