### ISSUE TITLE
Query json object with a condition on attribute does not work

### ISSUE THREAD

**Issue by dotekien** [ohler55/ojg#189]
Hi,
Given json
{"a":"v"}
These following json queries will return empty or failed. What should the query look like to check if a given json object has attribute a with value v? Thank you

- $.a[?(@ == "v")]
- $.a=="v"
- $[?(@.a=="v")]

**Comment by ohler55** [comment]
The expression `$[?@ == 'v']` should work when used the Has function like this:

```golang
	data := map[string]any{"a": "v"}
	x := jp.MustParseString("[?$.a == 'v']")
	fmt.Printf("%s => %t\n", x, x.Has(data))
```

The JSONPath spec calls for single quotes for string value but OjG allows either single to double quotes. The way to look at the expression is that the filter has to filter on the top most data element or `$`. Using `@` is the iteration element which doesn't work if you want to verify `a` has a value of `v` and not any other element.

**Comment by dotekien** [comment]
It works! Thank you!
