### ISSUE TITLE
Error in floating point type when using oj. Parse string

### ISSUE THREAD

**Issue by Mr-TianLang** [ohler55/ojg#190]
version 1.25.0
 
code:
func Test_oj(t *testing.T) {
	num1 := 1.56930

	m := map[string]interface{}{
		"data": num1,
	}
	jsonStr, _ := json.Marshal(m)
	jsonPath, _ := oj.Parse(jsonStr)
	fmt.Println(jsonPath)
}

![image](https://github.com/user-attachments/assets/100eb5a7-8562-499c-a5d2-9333221212c7)
From debugging, it can be seen that the actual value is 0.000 billion 0001 more than the expected value

**Comment by ohler55** [comment]
What OS and hardware are you running on? I was able to reproduce and fix on MacOS and in a Linux arm64 VM but I see that what ever platform github is using is still failing. Changing the `ojg.DefaultOptions.FloatFormat` to `"0.16g"` or less should also take care of the issue on intel machines but I am not able to verify that here or at least not easily.

**Comment by ohler55** [comment]
Release v1.25.1 should take care of the issue on all architectures.

**Comment by Mr-TianLang** [comment]
os: ubuntu 24   x86_64
cpu AMD Ryzen 5 PRO 4650U with Radeon Graphics
I'll go test the 'precision' branch

**Comment by Mr-TianLang** [comment]
I tested with version 1.25.1 and did not encounter the above error. fantastic

**Comment by ohler55** [comment]
Great. Closing this issue then.
