### ISSUE TITLE
accept a struct / array of structs

### ISSUE THREAD

**Issue by marcelloh** [ohler55/ojg#26]
Perhaps this isn't possible, I didn't find it in the documentation

I have a struct that has to be converted to a json []byte array
What is the way to do this (if possible)
(i tried to understand if this is somewhere in the jp part, but didn't find a solution.)

also if possible: an array of structs...

**Comment by ohler55** [comment]
Both converting a struct to a []byte or string is done using reflection or by having the struct implement an interface. There are some examples in the write unit tests. If they are not enough I'd be glad to add some more complex ones.

**Comment by marcelloh** [comment]
hmmm, I only want to generate json and write it later. Is there another way not using write?
(Reason is that i want to store the generated json in cache so it can skip everything when it's in the cache)

**Comment by ohler55** [comment]
I'm not sure what you are trying to achieve with that. It would be far simpler to just use `oj.JSON(data)`. In your example, `strings.Builder` will never return an error on `Write()`. You can check the golang code. If you just want to feel comfortable by checking for errors you can try the `marshal` branch I suggested in your other issue #25 . The `oj.Marshal()` function does return both a `[]byte` and an error. An error is returned if you try to encode un-encodeable values such as a function or `chan`. That way you have a reason to check for errors.

**Comment by ohler55** [comment]
I think this should be closed as well. Do you agree?
