### ISSUE TITLE
Separate options for edge and max-depth in addition to -p

### ISSUE THREAD

**Issue by ohler55** [ohler55/ojg#36]

**Comment by onetom** [comment]
`edge` sounds like graph terminology; I would expect something related to `line` or `column` or `width` or `margin`.

`max-depth` reminds me of the `find` unix command :) i would expect something like `level`, from _nesting level_.

> I toyed with 80x3 and 80:3 but ended up with 80.3.

i was also surprised by this notation, but looks quite practical.
i can't remember seeing such an novel interpretation of it elsewhere.

what about `3/80` as in 3 levels per 80 chars?

or `80#3`, like 80 chars with number of levels?

or `80{3}`, which doesn't need escaping in bash nor zsh?
(`80[3]` errors with `zsh: no matches found: 80[3]`)
it kinda indicates nesting. the count limitation in regexps come to mind.

multiple options are unnecessarily verbose.
i vote for keeping a single `-p` for this purpose.
it helps interactive use greatly!

**Comment by ohler55** [comment]
Glad to have this conversation. Let me throw another parameter in the mix. Having the option to align keys has been suggested and I think it does improve readability in some case. I'd like to add that option as well. That makes 3 pretty parameters. Could be more in the future. If the parameter could be extendable that would probably be best.

How about using SEN format like `{width: 80 level: 3 align: true}`?

**Comment by ohler55** [comment]
I went with a dot separator so `80.3.true` for the full set of options. It seems okay. What do you think?

**Comment by ohler55** [comment]
Latest is in v1.8.0. Happy to discuss further.
