### ISSUE TITLE
expanding characters to unicode

### ISSUE THREAD

**Issue by delanym** [ohler55/ojg#37]
Why are some characters being expanded (as the default output)?

```
{
  "6": {
    "morgan": "ZILFER",
    "summary": "This code is used to describe the zilfer.",
    "body": [
      "<p><b>Note:</b> Some of these zilfer types and accounts are only applicable to this platypus.</p>"
    ]
  }
}
```

When I run oj without switches, I get

```
{
  "6": {
    "morgan": "ZILFER",
    "summary": "This code is used to describe the zilfer.",
    "body": [
      "\u003cp\u003e\u003cb\u003eNote:\u003c/b\u003e Some of these zilfer types and accounts are only applicable to this platypus.\u003c/p\u003e"
    ]
  }
}
```

How do I stop it (without using sen)?

**Comment by ohler55** [comment]
Those characters are commonly escaped as they cause problems with HTML. I could add an options to turn on or off HTML safe writing. What are your thoughts on that?

**Comment by ohler55** [comment]
Try the html-safe branch and set Options.HTMLUnsafe to true.

**Comment by delanym** [comment]
Thanks. I don't want the JSON parser messing with my basic ASCII strings. But if its more efficient/safer I get it. I just came here from an article that recommends this as a way to prettify the JSON.

I followed your installation instructions, so Im not sure how to get the branch:
**go get github.com/ohler55/ojg
go get github.com/ohler55/ojg/cmd/oj**

**Comment by ohler55** [comment]
Ahh, to get the branch you have to checkout and build from GitHub. My apologies. Give me a few days and I'll make a new release. Hopefully with the alignment option as well.

**Comment by ohler55** [comment]
New release v1.7.1 should allow you to see the new options.

**Comment by delanym** [comment]
Got it, thanks
