### ISSUE TITLE
invalid number

### ISSUE THREAD

**Issue by jmccormick2001** [ohler55/ojg#45]
Hi, I'm using your API to parse some json, hitting an error with
data like this:
      "ECCENTRICITY": 8.26e-05,

the error is "invalid number at x:xxxxxx"

curious if that is an invalid number or if its a bug in the parsing?  if I'm understanding the JSON spec, I think its a valid number but really not sure.

I'm using github.com/ohler55/ojg v1.2.0

many thanks.

**Comment by ohler55** [comment]
You are probably right. I had assumed that the exponent followed the same rules as the integer portion but looking at the spec again leading zeros are acceptable. I'll get that fixed over this weekend.

**Comment by ohler55** [comment]
Can you try the latest version which is v1.9.3. I was not able to reproduce the issue.

**Comment by jmccormick2001** [comment]
seems to not parse using 1.9.3, here is some code I'm using to 
get the JSON and parse it.

    url := "https://api.spacexdata.com/v4/starlink"
    resp, err := http.Get(url)
    if err != nil {
        panic(err)
    }

    var body []byte
    if resp.StatusCode == http.StatusOK {
        body, err = ioutil.ReadAll(resp.Body)
        if err != nil {
            panic(err)
        }

        os.Stderr.WriteString(fmt.Sprintf("read %d bytes\n", len(body)))
    } else {
        panic(fmt.Errorf("invalid response code from GET %d\n", resp.StatusCode))
    }

    os.Stdout.WriteString(string(body))

    _, parseError := oj.Parse(body)
    if parseError != nil {
        panic(parseError)
    }

**Comment by ohler55** [comment]
I'll work with that and see what the issue is. Thanks.

**Comment by ohler55** [comment]
And v1.9.4 is released with the fix!

**Comment by jmccormick2001** [comment]
tests out!  many thanks!  nice repo/package you are developing.
