### ISSUE TITLE
Unmarshaling Type difference from json package

### ISSUE THREAD

**Issue by raidancampbell** [ohler55/ojg#52]
I'm unsure if this is expected behavior, so I wanted to ask before figuring out recomposers.  By default, the standard library's `json.Decode` function will turn JSON numbers into float64s ([ref](https://golang.org/src/encoding/json/decode.go#L53)) for unmarshals to `map[string]interface{}`, while OjG looks like it tries parsing as an int, and falls back to a float if unsuccessful.

`jsoniter` follows the same behavior of the standard library, and our code has later type checks on certain fields making any migration a bit more involved than a drop-in.  See the below code snippet for details:

```go
func TestUnmarshal(t *testing.T) {
	j := []byte(`{"plain":1, "full_decimal":1.0,
			"negative":-1, "full_negative":-1.0,
			"zero":0,  "full_zero":0.0}`)

	var stdlib, ojg map[string]interface{}
	err := json.Unmarshal(j, &stdlib)
	err2 := oj.Unmarshal(j, &ojg)

	if err != nil || err2 != nil {
		panic("oh no")
	}

	for key := range stdlib {
		if stdlib[key] != ojg[key] {
			stdType := reflect.TypeOf(stdlib[key])
			ojgType := reflect.TypeOf(ojg[key])
			if stdType != ojgType {
				t.Errorf("mismatch between stdlib type '%v' and ojg type '%v' on key '%v'", stdType.String(), ojgType.String(), key)
			}
		}
	}
}
/* returns:
mismatch between stdlib type 'float64' and ojg type 'int64' on key 'plain'
mismatch between stdlib type 'float64' and ojg type 'int64' on key 'negative'
mismatch between stdlib type 'float64' and ojg type 'int64' on key 'zero'
*/
```

**Comment by ohler55** [comment]
What you are asking for makes sense. Of course if a number in JSON is an integer then in some cases it is nice to have it be an integer in the unmarshalled result. Maybe the best of both is to have `Marshal` returns float64s and then leave `oj.Parse` to keep JSON integers as `int64`. What do you think of that approach?

**Comment by raidancampbell** [comment]
That seems like an excellent approach.  When faced with choices for json marshaling / unmarshaling, it's been an excellent user experience to simply swap out `json.Unmarshal` for `jsoniter.Unmarshal` for `ojg.Unmarshal`.

**Comment by ohler55** [comment]
I'm in the process of a struct Marshal speedup so I'll add that option at the same time. Look for it next week.

**Comment by ohler55** [comment]
A bit longer I'm afraid.

**Comment by ohler55** [comment]
If you don't mind working off a development version I have a branch named "pointer" that has the change in it. While the API is compatible there are a number of speedups with marshalling structs. Added more options like MustParse.

**Comment by raidancampbell** [comment]
I'm in absolutely no hurry here, for the time being I'm sticking with `jsoniter`'s implementation.  Some more pressing stuff came up in the meantime so I won't be free to test out the change for another week or two.

I appreciate the MustParse though, I'm looking forward to giving it a spin!

**Comment by raidancampbell** [comment]
It's looking like the more pressing stuff is also bound by various JSON marshaling/unmarshalings.  I see the `pointer` branch was merged into `develop` recently: is that good to play around with?

**Comment by ohler55** [comment]
It is good enough to play around with. I am making my way through unit tests now and will have some changes in the top level (ojg) package but all those functions are for shared internal use only. If you run into anything you would like changed let me know and we can discuss it.

**Comment by ohler55** [comment]
v1.11.0 has been released.

**Comment by raidancampbell** [comment]
Confirmed type differences resolved, thanks for the prompt work!  Unfortunately I found another unrelated discrepancy with the behavior of the standard library's json package and opened #54 for tracking
