### ISSUE TITLE
Custom Marshalers and Unmarshalers not respected

### ISSUE THREAD

**Issue by raidancampbell** [ohler55/ojg#54]
When invoking `oj.Marshal` or `oj.Unmarshal`, any custom JSON [Un]Marshalers are expected to be invoked.  This behavior is seen in the standard library's `json` package.  Below is a code snipped showing the issue:
```go

type Decimal struct {
	value *big.Int
	exp   int32
}

func (d Decimal) MarshalJSON() ([]byte, error) {
	return []byte(fmt.Sprintf("\"%d,%d\"", d.value, d.exp)), nil
}

type TestStruct struct {
	Outer  bool   `json:"outer"`
	Decimal Decimal `json:"decimal"`
}

func TestMarshall_ArrCompatibility(t *testing.T) {

	strct := []TestStruct{{
		Outer:   true,
		Decimal: Decimal{big.NewInt(5), 2},
	}}

	stdBuf, err := json.Marshal(strct)
	tt.Nil(t, err)

	ojBuf, err := oj.Marshal(strct)
	tt.Nil(t, err)


	tt.Equal(t, true, strings.Contains(string(stdBuf), "\"decimal\":\"5,2\""))
	if !strings.Contains(string(ojBuf), "\"decimal\":\"5,2\"") {
		t.Fatal("Mashaled JSON did not invoke custom Marshaler.  Expected: \"decimal\":\"5,2\" to be present.  Got: ", string(ojBuf))
	}
}
```
which returns the following:
```
Mashaled JSON did not invoke custom Marshaler.  Expected: "decimal":"5,2" to be present.  Got:  [{"decimal":{},"outer":true}]
```

**Comment by ohler55** [comment]
I completely missed that. Branch "marshalers" has an implementation and I will add unit tests over the next day or two.

**Comment by ohler55** [comment]
Unit tests added.

**Comment by raidancampbell** [comment]
hmmm. I can see that the `MarshalJSON` func is invoked in your test, but I'm not able to replicate it in my above code.  It looks like the `appendJSON` type switch is passing over `json.Marshaler` and just hitting the default.  The incoming data to that function is `[]TestStruct` and the `appendDefault` code doesn't look to recurse back into the function to check for a `json.Marshaler` inside the struct

**Comment by ohler55** [comment]
I'll add some more tests tomorrow. Just got back tonight from taking pictures of moose and feeding mosquitoes. :-)

**Comment by ohler55** [comment]
Pushed another update that adds the missing support to struct members. More unit tests are needed but a modified version of your test is included in the struct_test.go.

**Comment by ohler55** [comment]
OjG v1.11.1 has the fix and has been released. The https://github.com/ohler55/compare-go-json project has also been updated with the latest versions.

**Comment by ohler55** [comment]
Can this be closed?

**Comment by raidancampbell** [comment]
whoops, yes.  I'm out of town and unable to give this a more thorough verification, but the diffs looks good to me!
