### ISSUE TITLE
Query with bracket notation and object literals (@ in attribute name)

### ISSUE THREAD

**Issue by hspaay** [ohler55/ojg#67]
Looking to use this library for querying a directory of ['Thing Descriptions'](https://www.w3.org/TR/wot-thing-description11/) 
The vocabulary of a TD includes an attribute named "@type". Is it possible to query such attribute?

According to the [json-path-comparision](https://cburgmer.github.io/json-path-comparison/), the filter expression with [bracket notation and current object literal](https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_bracket_notation_and_current_object_literal.html) (for example: "$[?(@['@type']=="sensor")]"  is supported by this library but this returns an empty result.

What did work was the bracket notation without the object literal, eg $[?(@['type']=="sensor)]. 

Btw, many thanks for this library. It just seems to work without the usual head banging :). Great job!

**Comment by ohler55** [comment]
That is interesting. Sounds like a bug that will need to be fixed.

**Comment by hspaay** [comment]
Simple test example that shows this.
Query1 returns 1 item in the result. Query 2 returns no items in the result. The only difference is change from query of 'type' to  '@type', both using the bracket notation.
Hope this helps.

```golang
func TestQuery2(t *testing.T) {
	store := make(map[string]interface{})

	jsondoc := `{
		"item1": {
			"id": "item1",
			"type": "type1",
			"@type": "attype1"
		},
		"item2": {
			"id": "item2",
			"type": "type2",
			"@type": "attype2"
		}
	}`
	query1 := `$[?(@['type']=="type1")]`           // bracket notation without object literal
	query2 := `$[?(@['@type']=="type1")]`          // with object literal 

	err := json.Unmarshal([]byte(jsondoc), &store)
	assert.NoError(t, err)

	jpExpr, err := jp.ParseString(query1)
	assert.NoError(t, err)
	result := jpExpr.Get(store)         // this returns one result as expected
	assert.NotEmpty(t, result)

	jpExpr, err = jp.ParseString(query2)
	assert.NoError(t, err)
	result = jpExpr.Get(store)
	assert.NotEmpty(t, result)      // this fails with empty result
}
```

**Comment by ohler55** [comment]
Thanks, that helps.

**Comment by ohler55** [comment]
I found the problem. `query2` is checking for `@type` being equal to `"type1"`. There is no match for that in the json doc. There is a match for `"attype1"` though. This worked for me:

``` golang
func TestFilterAt(t *testing.T) {
	jsondoc := `{
			"item1": {
				"id": "item1",
				"type": "type1",
				"@type": "attype1"
			},
			"item2": {
				"id": "item2",
				"type": "type2",
				"@type": "attype2"
			}
		}`
	store := oj.MustParseString(jsondoc)
	x := jp.MustParseString(`$[?(@['@type']=="attype1")]`)
	result := x.Get(store)
	tt.Equal(t, 1, len(result))
}
```

That test has been added to the jp/get_test.go file in the project.

**Comment by hspaay** [comment]
Arggh, that was a silly mistake with my test cases. 
Sorry for wasting your time and thank you for looking into it.

**Comment by ohler55** [comment]
All good. It lets me know there are some users out there. :-)
