### ISSUE TITLE
reflect.Value.Addr of unaddressable value Error

### ISSUE THREAD

**Issue by Gusted** [ohler55/ojg#68]
Hello,

Since https://github.com/ohler55/ojg/releases/tag/v1.10.4-develop we are running into an error while `Marshal`-ing a struct which includes the `time.Time`

A very tiny reproduce-able case
```golang
type MinimalStyle struct {
	CreatedAt time.Time
}

func TestJSON(t *testing.T) {
	testCase := MinimalStyle{
		CreatedAt: time.Unix(0, 0),
	}
	_, err := oj.Marshal(testCase)
	if err != nil {
		t.Fatalf("Marshal error: %s", err)
	}
}
```

The stacktrace that was shown in the debugger seems to indicate the error originates from this line of code: https://github.com/ohler55/ojg/blob/10b6e9cb9f3f698966eb54ab45afa64e5f38ac72/oj/jsonmarshaler.go#L21

Callstack:
![image](https://user-images.githubusercontent.com/25481501/127406747-fb640c0e-8387-427c-b639-50c2358a3c20.png)

Regards,
Gusted

**Comment by ohler55** [comment]
Thank you for the test case. I'll get it fixed. Might take a day or two.

**Comment by ohler55** [comment]
The branch "can-not-addr" has the fix. If it works okay for you I'll release.

**Comment by Gusted** [comment]
Many thanks! That fixes the issue.

**Comment by ohler55** [comment]
v1.12.3 released

**Comment by Gusted** [comment]
Thank you!
