### ISSUE TITLE
Better error message for oj.Unmarshal

### ISSUE THREAD

**Issue by TheRightMouse** [ohler55/ojg#69]
First of all, thanks for the awesome library. I just wanted to report that when `oj.Unmarshal` is called on a struct and fails, it provides an unhelpful error message. Here's a minimal example:

```go
type Query struct {
	Level  string
	Query  map[string]interface{}
	Expand bool
	Limit  int
}

func main() {
	queryJSON := `{
	"Level": "Series",
	"Query": {},
	"Expand": false,
	"Limit": true
}`

	var query Query
	err := oj.Unmarshal([]byte(queryJSON), &query)
	if err != nil {
		fmt.Println(err)
	}
}
```

The error here is that a `bool` is attempted to be unmarshaled onto an `int`. Here's an example of the error message I get: `&{ map[Query:0xc000060050 main/Query:0xc000060050]}`.

Playground: https://play.golang.org/p/ytyPl0SF_no

**Comment by ohler55** [comment]
I has been fixed in the develop branch and will be in the next release.

**Comment by ohler55** [comment]
v1.12.3 released.

**Comment by TheRightMouse** [comment]
Thanks for fixing.
