### ISSUE TITLE
Can't build on 32-bit CPU

### ISSUE THREAD

**Issue by FZambia** [ohler55/ojg#72]
Hello @ohler55. Awesome library, we looked at several JSON path implementations and your work is just beautiful.

We came across a problem compiling Grafana with ojg as a dependency on 32-bit CPU due to usage of `math.MaxInt64`.

Simple example which reproduces this:

```
cd cmd/oj
GOOS=linux GOARCH=arm go build
# github.com/ohler55/ojg/jp
../../jp/get.go:414:8: constant 9223372036854775807 overflows int
../../jp/get.go:975:8: constant 9223372036854775807 overflows int
../../jp/node.go:263:8: constant 9223372036854775807 overflows int
../../jp/node.go:538:8: constant 9223372036854775807 overflows int
../../jp/parse.go:356:13: constant 9223372036854775807 overflows int
../../jp/parse.go:363:13: constant 9223372036854775807 overflows int
../../jp/slice.go:28:10: constant 9223372036854775807 overflows int
```

Related: https://github.com/golang/go/issues/23086

I think in most cases here it's safe to switch using `math.MaxInt` – but I am not sure at the moment whether it's safe to switch everywhere throughout a library, maybe there is a need to explicitly use `int64` type (for example, for `BigLimit` boundary).

**Comment by ohler55** [comment]
Thanks for the find. I would not have expected that since the documentation makes no mention of the restriction. I'll take a look at what the best work around is.

**Comment by FZambia** [comment]
Yep, agree – this is not obvious at all. One important thing I just realized is that `math.MaxInt` was [only added in Go 1.17](https://golang.org/doc/go1.17#math), so relying on it will make it impossible to build `ojg` on Go < 1.17.

**Comment by ohler55** [comment]
The MaxInt64 is meant to be the limit on and array length for filters. I suspect no one could reasonably complain about a maximum of 32768.

**Comment by ohler55** [comment]
The develop branch has what I hope is a fix.

**Comment by ohler55** [comment]
v1.12.6 released with the fix.

**Comment by FZambia** [comment]
@ohler55 thanks!

Just checked it out: `21474836487` is still larger than `2147483647` which is a maximum value for int32, so there are still errors:

```
❯ GOOS=linux GOARCH=arm go build
# github.com/ohler55/ojg/jp
../../jp/get.go:420:8: constant 21474836487 overflows int
../../jp/get.go:981:8: constant 21474836487 overflows int
../../jp/node.go:262:8: constant 21474836487 overflows int
../../jp/node.go:537:8: constant 21474836487 overflows int
../../jp/parse.go:355:13: constant 21474836487 overflows int
../../jp/parse.go:362:13: constant 21474836487 overflows int
../../jp/slice.go:27:10: constant 21474836487 overflows int
``` 

Looks like a typo in a number - maybe using `math.MaxInt32` will be better here?

**Comment by ohler55** [comment]
Typo, darn. I'll try again.

**Comment by ohler55** [comment]
Please try the "32-bit" branch.

**Comment by FZambia** [comment]
Yes, 32-bit branch seems fine, thanks!
