### ISSUE TITLE
oj.Unmarshal doesn't use custom unmarshalers

### ISSUE THREAD

**Issue by right-mouse** [ohler55/ojg#73]
`oj.Unmarshal` doesn't seem to use custom unmarshaling rules defined by implementing the [json.Unmarshaler](https://pkg.go.dev/encoding/json#Unmarshaler) interface.

Simple playground example: https://play.golang.org/p/-cbMOSel_C6

**Comment by ohler55** [comment]
v1.12.6 released with the fix.

**Comment by right-mouse** [comment]
Seems to work when Unmarshal is called on the `json.Unmarshaler` directly, but it doesn't work if the `json.Unmarshaler` is part of a struct. Updated playground example: https://play.golang.org/p/CygEQ9xDR2I

**Comment by ohler55** [comment]
Please try the '32-bit' branch.

**Comment by right-mouse** [comment]
Works now. Thanks for the fix.

**Comment by ohler55** [comment]
Thanks. I'll release when the 32bit fixes are verified.
