### ISSUE TITLE
May some bug on oj.Parse

### ISSUE THREAD

**Issue by zzzzwc** [ohler55/ojg#85]
When I parse an incomplete json like `{"time":"2021-08-16 12:12:15","a":"5","b":"5"` by oj.Parse  it return a nil result and a **nil error**.

**Comment by ohler55** [comment]
Looking into it now.

**Comment by ohler55** [comment]
Please try the no-error-on-not-closed branch. I've got a few print statements in there trying to get back to 100% coverage so it might take a couple of days to get the release out.

**Comment by ohler55** [comment]
Released v1.13.1

**Comment by zzzzwc** [comment]
> Released v1.13.1

great
