### ISSUE TITLE
Private fields should be ignored when Unmarshaling

### ISSUE THREAD

**Issue by right-mouse** [ohler55/ojg#93]
When unmarshaling or recomposing to a struct, if a key matching a private field is found, the private field is attempted to be set resulting in a panic:
```
reflect: reflect.Value.Set using value obtained using unexported field
```

Playground demonstration: https://go.dev/play/p/r6oam713GJo

**Comment by ohler55** [comment]
Please try the "respect-private" branch.

**Comment by right-mouse** [comment]
Looks to be working as expected on that branch.

**Comment by ohler55** [comment]
Thanks

**Comment by ohler55** [comment]
Released

**Comment by right-mouse** [comment]
Thanks for the quick fix.
